# Generated by Django 4.1.7 on 2023-03-31 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_calendar_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Master',
            new_name='Specialist',
        ),
    ]
