# Generated by Django 4.1.7 on 2023-04-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_master_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='status',
            field=models.IntegerField(choices=[(0, 'Status 1'), (1, 'Status 2'), (2, 'Status 3'), (3, 'Status 4')], default=0),
        ),
    ]
