# Generated by Django 4.1.7 on 2023-04-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_specialist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='master',
            new_name='specialist',
        ),
        migrations.AlterField(
            model_name='specialist',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Rank 1'), (2, 'Rank 2')], default=0),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='status',
            field=models.IntegerField(choices=[(1, 'Status 1'), (2, 'Status 2'), (3, 'Status 3'), (4, 'Status 4')], default=0),
        ),
    ]
