# Generated by Django 4.1.7 on 2023-04-02 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_calendar_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='master',
            new_name='specialist',
        ),
    ]
