# Generated by Django 4.1.7 on 2023-04-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_rename_master_booking_specialist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendar',
            new_name='WorkSchedule',
        ),
    ]
