# Generated by Django 4.1.7 on 2023-04-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_service_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.DurationField(),
        ),
    ]
